### ISSUE TITLE
 could you provide Python code for  generation data

### ISSUE THREAD

**Issue by sam-1219** [samedsaka/syntheticddos#1]
could you provide Python code for  generation data

**Comment by samedsaka** [comment]
Thanks for your message. You can find the details in the corresponding article available at [this link](https://ieeexplore.ieee.org/abstract/document/10538767).

**Comment by sam-1219** [comment]
yes，I had review your paper。it is valuable for my study

**Comment by gubertoli** [comment]
@sam-1219 probably this link helps: https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer
